### ISSUE TITLE
feature[animation]: illustrate error text replacing help text

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1653]
## feature[animation]:illustrate error text replacing help text

This is a situation where showing the micro-animation will really help people understand. This is also an animation that can appear in several places on the site.

### Behavior: Text input

Help text:

![image](https://user-images.githubusercontent.com/43144260/91860319-8660c000-ec39-11ea-9d0a-e95d27e77c29.png)

Error text should animate over help text:

![image](https://user-images.githubusercontent.com/43144260/91860385-98426300-ec39-11ea-8732-d492016d0db3.png)

### Behavior: Dropdown

Help text:

![image](https://user-images.githubusercontent.com/43144260/91860646-eb1c1a80-ec39-11ea-8cb9-ca81b3b68ab4.png)

**Error text animates over the help text:**

![image](https://user-images.githubusercontent.com/43144260/91860702-fff8ae00-ec39-11ea-957b-52120677e2b8.png)

**Potential places to put this animation:**

- Guidelines > Content > Error messaging
- Patterns > Forms > Errors and validation
- Components > Text input > Help text
- Components > Dropdown > Help text (this will require a separate video, same animation but using dropdown component instead of text input component)

**Example animation on Material.io (something like this with our timing/easing is what we would like)**

https://material.io/components/text-fields#anatomy

![image](https://user-images.githubusercontent.com/43144260/91857671-316f7a80-ec36-11ea-8bfa-eae62f3343f4.png)

## To-do

- [ ] Animation size: 8-column animation (608 x 304px exported at 2x); vertically centered, 64px side margins
- [ ] Follow Carbon motion guidelines (timing, easing/motion curves)
- [ ] Make an animation for text input and one for the dropdown component (dropdown assets to come)
- [ ] Animation can't loop due to accessibility constraints, it will have to have a player so the user can play and pause

**Here's a mini storyboard for Text input**

Enabled text input:
![1_enabled](https://user-images.githubusercontent.com/43144260/91883171-0f83f100-ec52-11ea-81e5-0c6a1ce48b14.png)

<br>

User types address:
![2_typing](https://user-images.githubusercontent.com/43144260/91883173-101c8780-ec52-11ea-9ae3-3209f8d65748.png)

<br>

Error replaces help text:
![3_error](https://user-images.githubusercontent.com/43144260/91883174-101c8780-ec52-11ea-9763-8887d9d40d8f.png)

[Error_message_svg_assets.zip](https://github.com/carbon-design-system/carbon-website/files/5157702/Error_message_svg_assets.zip)

**Comment by johnbister** [comment]
@jeanservaas @janchild 

Hello! Just wanted to send a really quick test I did to make sure I'm on the right track.  I apologize if it loops (I can only upload gifs to GitHub issue comments).  I'll make sure the motion is polished and doesn't loop for the final output.

A couple of questions:

1. What is the final file output? mp4?

2. Do you know how many frames per second were used on previous animations? 30?

Thanks for sending out this first issue so I can experiment and figure out the best workflow.

![1653_Test](https://user-images.githubusercontent.com/70543333/91899011-2df1e880-ec62-11ea-8eb7-ff4cd35352bd.gif)

**Comment by mjabbink** [comment]
Agree. We just need to ask them and see if one of the 3 can do it whenever we want to do a review.

**Comment by jeanservaas** [comment]
@johnbister here are the dropdown assets. After you put together a cut of this one, I'll reach out to those guys above and arrange for one of them to review it. Again, @janchild may want to change the example copy

**step 1: enabled dropdown with helper text**

<img width="365" alt="image" src="https://user-images.githubusercontent.com/43144260/92518044-beda3e00-f1e5-11ea-9feb-a02dc2bb9cd3.png">

**step 2: user opens dropdown and hovers but does not make a selection**

<img width="383" alt="image" src="https://user-images.githubusercontent.com/43144260/92518137-e3ceb100-f1e5-11ea-8a2f-58612f97b5aa.png">

**step 3: dropdown closes an error message happens because user did not make a choice**

<img width="346" alt="image" src="https://user-images.githubusercontent.com/43144260/92518226-0234ac80-f1e6-11ea-8283-91eb30294761.png">



[dropdown_assets.zip](https://github.com/carbon-design-system/carbon-website/files/5190532/dropdown_assets.zip)

**Comment by johnbister** [comment]
![1653_dropdown_v1](https://user-images.githubusercontent.com/70543333/92759918-d5070c00-f355-11ea-97b5-730c38d03a7a.gif)

@jeanservaas @janchild Here is the first go at the dropdown animation.  I figure it would be good to have a first draft of all issues for this sprint ready before I meet with another motion designer for review. I should be ready for that by Monday (9/14) if you wanted to set something up or let me know if you'd like to reach out to one of them directly.  Thanks!

**Comment by shixiedesign** [comment]
Hey there I think the general motion is good but it's hard to review gifs because it's unstable frame rate. Can you post the videos?
- The motion videos on the site are Apple ProRes renders uploaded to Vimeo so essentially MP4s. But we relied on Vimeo to do the conversion. 
- Frame rate is 30

**Comment by johnbister** [comment]
Thanks @shixiedesign Here are the MP4s.  Does github let you upload MP4 directly for an easier preview? I've been uploading gifs just because it's a supported file type.

[1653_dropdown_v1.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5233527/1653_dropdown_v1.mp4.zip)
[1653_v1.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5233530/1653_v1.mp4.zip)

**Comment by shixiedesign** [comment]
Hi @johnbister , just got to take a look at the videos and sorry for the delay - thanks for the reminder. The motion doesn't really matter in dropdown since the open drawer blocks it. So speaking specifically about the text input prototype, the main issue I see is the old helper text disappeared completely for a moment before the error text came in, making it seems discontinuous. To avoid it, you can mask out the helper text from top to bottom as the error text drops in. If it is difficult to implement, at least fade it out is my suggestion.

**Comment by johnbister** [comment]
Thanks! @shixiedesign I did a top-to-bottom mask and slight fade on the helper text so it feels more continuous.  Do you mind doing one last check for us?  

[1653_v2.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5261992/1653_v2.mp4.zip)

**Comment by shixiedesign** [comment]
LOOKS GOOD!! 👍

**Comment by johnbister** [comment]
@jeanservaas Here are the approved animations.  Please let me know if you need anything else for this.  Thanks!

[1653_vFinal.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5262181/1653_vFinal.mp4.zip)
[1653_dropdown_vFinal.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5262182/1653_dropdown_vFinal.mp4.zip)
