### ISSUE TITLE
Pattern status overview experience roadmap

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#188]
Create an experience roadmap for the pattern status page that defines which users stories will be delivered at each stage of the experience.

## **Cupcake** https://github.com/carbon-design-system/carbon-website/issues/186
**Considerations:**
- How breadcrumb navigation can be adapted in our site's UI.
- What does that third level of the site look like?
- Keeping the same depth of navigation, can dividers be used to separate the experimental patterns vs. the prod ones?

**Requirements** 
- [ ] As a Carbon dev/designer I want to be able to review the pattern roadmap so that I know which patterns are coming so I can plan my adoption and contribution around my product's schedule.
- [ ] As a Carbon dev/designer I want to filter control on the source of a pattern so I can only view patterns my team or org has created.
- [ ] As a Carbon dev/designer I can see patterns in different states so I can see which patterns are ready to be in products and which ones need feedback.
- [ ] As a Carbon dev/designer I can see a thumbnail representation of the pattern so I can quickly understand the scope of the pattern while browsing.
- [ ] As a Carbon dev/designer I can search based on the author...
- [ ] Metadata required:
- author
- source (business)
- Version
- state (Experimental, Beta, GA)
- Thumbnail view representing the pattern.

## **Birthday cake**
- Third level of navigation
- As a Carbon dev/designer I can log in with my W3id so the content I see will be curated to my project. (This is similar to what team Able already has implemented.) 

## **Wedding cake**
- As a Carbon dev/designer I can directly upload and edit pattern guidance and assets to the Carbon website so I don't have to go through the trouble of editing markdown and making PR's in github.
