### ISSUE TITLE
Component pages: Usage & Style tabs ☂️ 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2085]
After our big push in 2020 to update all component usage docs with the [new template](https://www.notion.so/carbondesignsystem/Component-documentation-2ffec1e5c38443f3bfbcf354c9504d59), these are the remaining components that still need to be updated:

### Completed
- [x] [Form](https://www.carbondesignsystem.com/components/form/usage) | https://github.com/carbon-design-system/carbon-website/pull/3356
- [x] [Number Input](https://www.carbondesignsystem.com/components/number-input/usage) | https://github.com/carbon-design-system/carbon-website/pull/3246
- [x] [Overflow menu](https://carbondesignsystem.com/components/menu-buttons/usage/) | https://github.com/carbon-design-system/carbon-website/pull/3765
- [x] [Progress indicator](https://carbondesignsystem.com/components/progress-indicator/usage/) | https://github.com/carbon-design-system/carbon-website/pull/3924
- [x] [Radio button](https://www.carbondesignsystem.com/components/progress-indicator/usage) | https://github.com/carbon-design-system/carbon-website/pull/2126
- [x] [Search](https://carbondesignsystem.com/components/search/usage/) | https://github.com/carbon-design-system/carbon-website/pull/3309
- [x] [Select](https://www.carbondesignsystem.com/components/select/usage) | https://github.com/carbon-design-system/carbon-website/pull/3282
- [x] [Tabs](https://www.carbondesignsystem.com/components/tabs/usage) | https://github.com/carbon-design-system/carbon-website/pull/2375 | https://github.com/carbon-design-system/carbon-website/pull/2376
- [x] [Text input](https://www.carbondesignsystem.com/components/text-input/usage) | https://github.com/carbon-design-system/carbon-website/pull/3115
- [x] [Tile](https://www.carbondesignsystem.com/components/tile/usage) | https://github.com/carbon-design-system/carbon-website/pull/2580
- [x] [Tooltip](https://www.carbondesignsystem.com/components/tooltip/usage) | https://github.com/carbon-design-system/carbon-website/pull/3655
- [x] [Tag](https://carbondesignsystem.com/components/tag/usage/) | https://github.com/carbon-design-system/carbon-website/pull/3912
- [x] [Slider](https://carbondesignsystem.com/components/slider/usage/) | https://github.com/carbon-design-system/carbon-website/pull/3789

(note: all pages have been updated to reflect the new structure but the content itself has not been updated or added too)

**Comment by sstrubberg** [comment]
For the Pagination page https://github.com/carbon-design-system/carbon-website/issues/3608
