### ISSUE TITLE
Carbon training for designers

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#2176]
An epic to house the effort of defining training needed to support designers with Carbon usage and adoption. 

Activities within this epic will include:

**Training content**
- [x] auditing other training content to formulate patterns and best practices for us to follow
- [x] reviewing 2019 Design Essentials videos for content
- [ ] revising existing tutorials on site
- [ ] begin gathering topics for training
- [ ] review Slack audit of most FAQ for topics, see Jillian for audit

Topics to include:
  - [ ] Use of grid, multiples of 2, alignment
  - [ ] tokens
 
**Testing and badging exploration**
- [ ] Conduct an audit of various tests
- [ ] Begin to formulate a multiple choice test that could lead to a badge

**Comment by johnbister** [comment]
Closing this due to shifting priorities and lack of resources.
