### ISSUE TITLE
[Data vis] Work tracking

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#239]
### Plan

- @shixiedesign to create designs for all pages as scoped in https://github.com/carbon-design-system/carbon-website/issues/208

- @alisonjoseph to create a branch & starting putting up pages based on wireframe https://github.com/carbon-design-system/carbon-website/issues/227
- @connor-leech to take a look at data vis documentation content: https://github.com/carbon-design-system/carbon-website/issues/238

### Pages under Data vis section include
Box folder containing Sketchfile of all pages: https://ibm.box.com/s/qkimsr1znekwze3q3bsvacs2b42hf7t5

- [x] Getting started (formally Develop) https://github.com/carbon-design-system/carbon-website/issues/364
- [x] Overview: https://github.com/carbon-design-system/carbon-website/issues/240
- [x] Charts: https://github.com/carbon-design-system/carbon-website/issues/241
- [x] Palettes: https://github.com/carbon-design-system/carbon-website/issues/242
- [x] Axis and labels: https://github.com/carbon-design-system/carbon-website/issues/243
- [x] Legends https://github.com/carbon-design-system/carbon-website/issues/387
- ~~Tooltips `issue to come`~~ out of scope
- [x] Dashboard https://github.com/carbon-design-system/carbon-website/issues/351
