### ISSUE TITLE
v11: add and update size images

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2408]
# Task
Create size images on the following V11 style tab pages. 

- [x] Accordion 
- [x] ~Button~ _Skip for now_
- [x] Content switcher
- [x] ~Data table~ _Skip for now_
- [x] Date picker
- [x] Dropdown (exists but has outdated names)
- [x] File uploader
- [x] Link (keep the current one)
- [x] ~Modal~ _Skip for now_
- [x] Number input
- [x] Overflow menu
- [x] Text input
- [x] Search
- [x] Select
- [x] ~Structured list~ _Skip for now_
- [x] ~Tabs~ _Skip for now_
- [x] Tags
- [x] Toggle

## How to create images:
This image will use the fixed image component on the website (we'll worry about this later) and needs an art board width of **736px**.

**Image sizes**
Image size should follow one of these ratios:
- 2:1 = 736 x 368
- 16:9 =  736 x 414
- 3:2 = 736 x 490
- 4:3 = 736 x 552
- 1:1 = 736 x 736

**Image layout**
The fixed image component keeps the size of the image true to pixel size and just adds white space to either side of the image as it grows. For this reason we do not recommend using horizontal rules to divide the components up like we do in a lot of our usage images. The size variants should just be evenly spaced (not too tight at least 32px is not more between variants) and centered in the image. The width of the component itself is up for interoperation but should be at least 32px  (48px is better)from the edges of the image. Don't over stretch the component, it should look natural. 

![image](https://user-images.githubusercontent.com/11670886/122101445-ea73ff80-cdd9-11eb-951e-79aa0bf67238.png)

**Image spec**
- The image should include a variant of all the sizes. 
- Each variant should be labeled with its size name. We include this in the component symbol itself, normally as the label name. 
- Each size should have use the spec brackets to identify the heights and include the px/rem value of the heights. Both the text and brackets use Magenta 60. You can either draw the brackets with the line [feature in Sketch](https://github.com/carbon-design-system/carbon-website/issues/2408#issuecomment-861739672) or use the symbol from Jeannie's production guidelines. 

![image](https://user-images.githubusercontent.com/11670886/122103110-da5d1f80-cddb-11eb-8eab-f7c0f202c5b4.png)
Example from: https://v11.carbondesignsystem.com/components/dropdown/style#sizes

- If a component contains multiple parts or sections and there is room to include them add them in to help with context.
![image](https://user-images.githubusercontent.com/11670886/122105024-ec3fc200-cddd-11eb-9a02-11a5350c6672.png)

## Exporting images
- Name the images: `component-style-size`
- Export them out at 2x and save them all together in a local folder.
- Be sure they have been added to the [master file](https://ibm.box.com/s/jaer3akhe2ytpwlwsxma5ykoxm58q7xu) on box

## Existing assets
Either open these assets through Box Drive to edit them and the images will be automatically added OR you can download the files and work locally then add them into the master file on Box Drive later.

- Current usage and style image file: https://ibm.box.com/s/jaer3akhe2ytpwlwsxma5ykoxm58q7xu
- Old usage image file: https://ibm.box.com/s/dk5bx73vmag6xyo7fta3zpveraojdcat
- Old style image file: https://ibm.box.com/s/jn05ykv35t9bmqvkgdb7z21n6s1dqpf8

If needed, pull in components from the Carbon libraries. If size variants don't exist yet in the library then draw them for the image (detach existing size and edit to correct size).

**Comment by aagonzales** [comment]
Examples of components that have size images already:
- Button: https://carbondesignsystem.com/components/button/style#sizes
- Dropdown: https://carbondesignsystem.com/components/dropdown/style#sizes

**Comment by aagonzales** [comment]
How to draw a bracket line:
![image](https://user-images.githubusercontent.com/11670886/122105498-78ea8000-cdde-11eb-9897-dcd8d2d7b05f.png)

**Comment by thyhmdo** [comment]
Updated images 
https://ibm.ent.box.com/folder/139467512584

Need the final review @aagonzales

**Comment by aagonzales** [comment]
They look good, just two things.
1. I forgot to tell you but the images should be exported out with the background included. I lot of them have transparent backgrounds
![image](https://user-images.githubusercontent.com/11670886/122788304-cdc54500-d27b-11eb-8a2d-8c4fece1a102.png)

2. The context menu is actually using the old style. Its been updated recently so let's use the [updated style](https://github.com/carbon-design-system/carbon/issues/6745#issuecomment-799595567). (Ideally this would be the time to updated all the context switcher images to have the new style as well)

**Comment by aagonzales** [comment]
# NEXT STEPS

## Create a local branch
Open a new branch on the v11 repo. One of us can walk you through this. You can't add images from the GitHub UI. 

## Adding the file images: 
1. Locate the image folder in file structure. Src > Pages > Components > Accordion > Images
   ![image](https://user-images.githubusercontent.com/11670886/122799541-788f3080-d287-11eb-8bee-dc9a3bf51c06.png) 
2. Right click the images folder to "Reveal in Finder"
   ![image](https://user-images.githubusercontent.com/11670886/122799801-c99f2480-d287-11eb-9bc5-25e35b73fe61.png)
3. Add (drag and drop) size image for specific component to the folder. Make sure it is inside the image folder
![image](https://user-images.githubusercontent.com/11670886/122800073-1edb3600-d288-11eb-8c31-9b3b7c9e2198.png)

## Adding image to the markdown file

1. In the same section for the component where you found the image folder, find the "Style" mark down file and open it by clicking on it. 
   ![image](https://user-images.githubusercontent.com/11670886/122800982-32d36780-d289-11eb-9adb-bede349f9b42.png)
2. Add the below code snippet under the size section. 

```
<div className="image--fixed">

![Alt text](images/type-file-name-here.png)

</div>
```
3. Add the correct file name where it says "type-file-name-here". It needs to be exactly how it appears in the images folder where you added it. 
   ![image](https://user-images.githubusercontent.com/11670886/122801870-4a5f2000-d28a-11eb-9f48-8e92eb7411f5.png)

4. Update the alt text inside the `[ ]` to say "Sizes for accordion". Alt text in the text that appears in a browser tooltip when you hover over the image. It is also the text that gets read out with a screen reader. 
   ![image](https://user-images.githubusercontent.com/11670886/122801791-30bdd880-d28a-11eb-9429-01c28ec7d500.png)

## Repeat
Repeat "Adding the file images" and "Adding image to the markdown file" for each component that has a size image. 

## Create a pull request
Once you've added all the images you'll need to create a Pull Request for review. Again someone on the team or I can walk you through this.

**Comment by thyhmdo** [comment]
Github request
https://github.com/carbon-design-system/carbon-website/pull/2418
