### ISSUE TITLE
Component accessibility tab(s) content updates

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#2669]
**About**

This effort was led by IBM Accessibility to improve the understanding of accessibility for designers and developers using Carbon, along with reviewing existing content and providing feedback or alternate approaches for components in the design system.

**Next steps**

Implement the following content updates for components on the Carbon website:

- [ ] [Accordion](https://ibm.box.com/s/odnqik0d2d1r9oeippw525y0zbbzurm8) component page content updates
- [ ] [Breadcrumb](https://ibm.box.com/s/3u18j2rxs3jpdxyqlay4tnq38mjly57e) component page content updates
- [ ] [Button](https://ibm.box.com/s/xmvru44x5gtcflvy2c17ylf1r2519pgw) component page content updates
- [ ] [Checkbox](https://ibm.box.com/s/7w2ct3oipewtd2nss444du1jelnwhk6c) component page content updates
- [ ] [Slider](https://ibm.box.com/s/dco7wrb74j2imrtdvygtlmd9zw3y2f2p) component page content updates

**Checklist**

- [ ] For each component, our team will need to:
  - [ ] Review content changes for the following pages:
    - [ ] Usage
    - [ ] Style
    - [ ] Accessibility
  - [ ] Provide feedback on content and work on improving with TODO (find owners)
  - [ ] Once content is finalized, implement the changes for the component page
    - [ ] Make sure images are up-to-date and available
    - [ ] Update content on the page
    - [ ] _Note: some content may be incompatible with a current release and may be appropriate with a future release, call that out if so_
  - [ ] When submitting a PR, make sure to include (TODO: owners) as reviewers

**Comment by joshblack** [comment]
## Notes

### December 14th, 2021

Participants

- Michael Gower
- Lauren Rice
- Jessica Lin
- Shari Trewin

**Breadcrumb**

- Note: implementation for "overflow" breadcrumb needs to be built or scheduled to be built
- Make sure example with overflow menu has a simpler label (like more links or more breadcrumbs)

**Comment by mbgower** [comment]
@joshblack potentially this is redundant with the different discussions and issues I've opened?
