### ISSUE TITLE
Updating the progress bar in code 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#2726]
## Updating the progress bar in code 
Related issue: https://github.com/carbon-design-system/carbon-website/pull/2688

**Tasks** 
- [ ] Adding statuses (error, success, loading)
- [ ] Adding variants (determinate, indeterminate)
- [ ] Adding sizes (big and small)
- [ ] RTL support 
- [ ] From Indeterminate to determinate (when enough information is gathered to end the load animation)
