### ISSUE TITLE
Carbon Next: Link to Carbon platform from current Carbon website

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3146]
Once we launch v1, we need to link to the [new Platform](https://next.carbondesignsystem.com/) from our [current carbon website](https://carbondesignsystem.com/). Since we are not completely replacing PALs just yet and nothing is being deprecated, the callout does not need to be too flashy. We will also be replacing the community index with platform information.

**Tasks:**
- [x] Explore possible design options and placements
   - Banner
   - Tile
   - Homepage callout
- [x] Decide direct and create final spec
   - Include responsive strategy 
- [x] Create issue for dev: https://github.com/carbon-design-system/carbon-website/issues/3179

---
[Figma file](https://www.figma.com/file/H3kWgBYKdMzov7LIZ1BlHa/Next-crosslinks?node-id=1%3A7738) with explorations

**Comment by aagonzales** [comment]
## Final banner spec
[Figma file](https://www.figma.com/file/H3kWgBYKdMzov7LIZ1BlHa/Next-crosslinks?node-id=67%3A6733)

<img width="3910" alt="Group 1" src="https://user-images.githubusercontent.com/11670886/192641440-a3e1939d-4f87-4d36-a522-e509d70804a5.png">
