### ISSUE TITLE
Data table: Combination of the selectable and the expandable

### ISSUE THREAD

**Issue by lsi117** [carbon-design-system/carbon-website#3394]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
Combination of the selectable and the expandable data table.

Could there be a combo-data table? I was thinking of combining both the expanded and the selectable table version into one. 

I wasn't able to come across this in Carbon V11. I didn't find guidance on this within Carbon nor did I find this available within Figma Carbon library, unless I missed it. 

I've provided low-fi mockups of a combo-table.

This might be a design and development issue.

### Justification

We are utilizing this custom combo-table for the z/OS Cloud Broker.

![not-expanded](https://user-images.githubusercontent.com/23106233/219716915-953138ca-af7e-4c67-a8e9-4adc3afd44b9.jpg)

![expanded](https://user-images.githubusercontent.com/23106233/219716930-0e9d7cf8-312b-41af-afe9-d1e6903d9861.jpg)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3437
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/655
```

**Comment by aagonzales** [comment]
## Tasks:
- [ ] Add section to usage and style tab with images

**Comment by lsi117** [comment]
> exist

Oh, great! Thank you.
