### ISSUE TITLE
Contribution guidance: Clean-up and update content

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3407]
I got a question today concerning contributing docs and the image production guidelines. It made me take a look at what we have up in the [contributing section](https://carbondesignsystem.com/contributing/overview/) right now on the website. I think the whole section could use some clean-up and updating to reflect our current process and ecosystem.
- We don't talk about component code contributions (new or enhancements) anywhere. The component page is just around component website docs.
- The documentation page is pretty weak and also a little redundant with the component and pattern page.
- We talk a lot about how to document something but not necessarily what is required from a design and code perspective for the actual asset.
- Are any of the pages no longer relevant / need to be consolidated or removed?
- [This page](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#types-of-issues) would be great to surface to our site.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3460
- [ ] https://github.com/carbon-design-system/carbon-website/issues/2369
- [x] Based on the outcome of the audit, make issues for each page and refine/chunk out work into separate issues
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3600
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3622
- [ ] https://github.com/carbon-design-system/carbon/issues/14294
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3720
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3621
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3753
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3718
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3719
```
