### ISSUE TITLE
Sketch Maintenance Mode: Umbrella

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3475]
#### Open questions

- Do we need to update our license to avoid issues?
- [x] We updated our personal workspace to be subscription based so our libraries will remain intact.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3476
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3487
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3477
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3478
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3479
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3480
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3481
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3447
```
