### ISSUE TITLE
[Tile doc] Update tiles with feedback 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#3486]
Feedback received from Jeeyoung Yang and Kevin Camelo. Things to update: 

```[tasklist]
### Tasks
- [ ] Define more aspect ratios and provide examples for tiles
- [ ] Explain better the usage between Expandable tiles with default vs interactive
- [ ] Consider defining type pairing and spacing
- [ ] Provide suggestion for interactive element on clickable tiles instead of completely blocking the usage
- [ ] Update the hero image with experimental tiles

```

----
**1. Define more aspect ratios and provide examples for tiles**

Suggestion to add: possibly in the Usage > Sizing section, does it help to add recommended tile ratios (2:3, 3:4, 16:9, etc)? I personally always forgot about ratios when designing in product - I think it would be helpful for designers to keep in mind designing with the grid layout guidance.

**2. Explain better the usage between Expandable tiles with default vs interactive**

Expandable tiles were a bit confusing - what is the difference between default vs. interactive?

**3. Consider defining type pairing and spacing**

_**Style > Structure section**_: I think the spacing between subheading/heading/content could be clarified. This is very often one of the most inconsistent styling mistakes found in products. My understanding is that there should be no spacing in between subheading/heading, and the content spacing should be defined depending on the rest of the content structure. It would be helpful to define the details here.

**4. Suggestion for interactive element on clickable tiles instead of completely blocking the usage**

**Interactive elements on Clickable tiles**
This rule (see screenshot) gets broken quite often across the board— and the feedback we've heard from accessibility is that the interaction of a clickable tile with clickable links isn't inaccessible per say- but rather not recommended. My suggestion here would be to consider adding guidance for that use case instead of blocking it off completely.

![image](https://user-images.githubusercontent.com/77697351/230416879-c592304b-beb0-46fd-9cc6-ce594f3d89a8.png)

**5. Update the hero image with experimental tiles**

Nitty gritty, but the image [here](https://carbondesignsystem.com/components/tile/usage/#overview) from Cloud is the only image not updated with the new experimental tiles. We can provide a base Figma template for those updates to be made and share it with you if you'd like!

Other feedback

About **_disabled state tiles_**: I do see a need for clickable and selectable tiles. The two function like CTAs and are often used to evoke an action like creating something. When a specific user does not have the right access or the setup to click or select a given option, a disabled state should be shown.

More examples of the combination treatment of a page with both cards and tiles would be nice! In practice, combining both is hard to do well visually.
