### ISSUE TITLE
[Select] Doc update 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#3524]
```[tasklist]
### Tasks
- [x] Usage + Style tabs https://github.com/carbon-design-system/carbon-website/pull/3523
- [x] Update the Figma kit https://github.com/carbon-design-system/carbon-design-kit/issues/677
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3555
- [ ] https://github.com/carbon-design-system/carbon/issues/13008
```
