### ISSUE TITLE
Menu and Friends 🏖️ 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3563]
- Create website documentation for all components using `Menu`.
- Leverage existing documentation from [Sustainability PAL](https://pages.github.ibm.com/ai-applications/design/components/buttons/usage) and [Carbon for IBM Products PAL](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons/).

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3609
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/674
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/686
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/685
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/714
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3494
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3568
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3700
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3701
- [ ] https://github.com/carbon-design-system/carbon-website/pull/3765
- [ ] https://github.com/carbon-design-system/carbon/issues/14676
- [ ] https://github.com/carbon-design-system/carbon/issues/14918
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3790
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3791
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3792
- [x] [Slack announcement] Make the Slack announcement 📢
```

**Comment by thyhmdo** [comment]
Discussed with Anna and looks like we need to decide where will these components live in Doc + Figma. Here are initial suggestions. 

![Menu Organization Suggestions](https://github.com/carbon-design-system/carbon-website/assets/77697351/1fcf29eb-086f-4ffb-b11a-254ea1816d96)

**Comment by Huixh111** [comment]
ii
