### ISSUE TITLE
Prototype a new user journey for contribution (across our website, Github, and Slack interactions)

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-website#3600]
```[tasklist]
### Tasks
- [x] Map out proposed new user journey , including touchpoints contributors have on our website, Github, and Slack
- [x] Wireframe and draft content for contribution pages and UI.
- [x] Experimentation with changes to Github issues: our templates, labels, and perhaps task list or template help for our own team to better triage and support contributors.
- [ ] Stretch goal: a draft of what the Figma status page would look like in Github or airtable format.
- [x] Playback iterations - both Tuesdays of the sprint
```

**Comment by aubrey-oneal** [comment]
[In Figma,](https://www.figma.com/file/9pdTqNPVJCmDOAacm3Rnxp/Contribution?type=design&mode=design&t=flfijzvgYW98nGMe-0) see phase 4: prototyping to find wireframes for the site and a proposed new suer journey. While this content is WIP, we'll move ahead to prototyping.
