### ISSUE TITLE
Automate & sync updating `gatsby-theme-carbon` & `carbon-website` carbon version

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#3675]
There are issues occurring when the Carbon version that is in `gatsby-theme-carbon` and `carbon-website` become out of sync. In order to fix this we need to add automation to update the Carbon deps inside the Gatsby them with each release, and then update the Carbon and gatsby deps in the Carbon website. In that order. 😅 

This is the order of operations

> 1. Normal Carbon [release](https://github.com/carbon-design-system/carbon/blob/main/docs/release.md#process) process
> 2. Update Gatsby theme with latest Carbon version
> 3. Release Gatsby theme
> 4. Update Carbon Website to latest Carbon and Gastby in the same PR

**Todo:**

```[tasklist]
### Tasks
- [x] https://github.com/carbon-design-system/carbon/pull/14352
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1332
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3688
```
