### ISSUE TITLE
[Psych catalog] Add Psychology Catalog to Carbon website

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#3808]
Cameron Calder and Jeff Longshore have been working on building a Psychology Catalog —  a collection of external links to psychology concepts, memory mechanics, learning methods, and gaming influences. It’s meant to be a helpful resource to designers, informing them as they make customer experience decisions.

Jeff has been working on building out this catalog in Gatsby so it will be ready to hand off to our devs. The catalog is driven by a .json file and users are able to filter multiple topics at once and search simultaneously. They are working on the alignments and the content on their end. 

One thing to note here is that Jeff is waiting on our final spec for the interactive/filter tags to finalize the catalog.
- [x] Specs sent

## Content
<img width="1408" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/43144260/27fcd15f-9ea3-4c32-b0a7-43e1eda5c353">

## In context in Gatsby

<img width="903" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/43144260/fc6f3660-ca8c-4262-80c7-c6149ff968d4">

<img width="1135" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/43144260/9c2b4e3e-d77f-49bd-989e-7436c75d6731">

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3843
- [x] https://github.com/carbon-design-system/carbon-website/issues/3845
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3844
- [ ] [Psych catalog] Implementation
```

**Comment by jeanservaas** [comment]
This epic is blocked by https://github.com/carbon-design-system/carbon-website/issues/3888
