### ISSUE TITLE
docs: revise order of sections on component Usage tabs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3820]
## Acceptance criteria
- With the new design specs that come out of [this issue](https://github.com/carbon-design-system/carbon/issues/15279), we will need to reshuffle some of the sections on our Usage tabs for all components.
  - Change order of content sections
  - Change order of anchor links

- [ ] *Note: We can not start this issue till the [dev implementation](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1377) of the design spec is complete.
----

**New section order**
The new order of sections on component Usage tabs will be as follows:
 - Live demo
   - Component status
- Overview
   - When to use
   - When not to use (optional)
- All other sections

----

```[tasklist]
### Tasks
- [ ] Update the content template on the contribution page
- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Contained list
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] Dropdown (Dropdown/Multiselect/Combobox)
- [ ] File uploader
- [ ] Form
- [ ] Inline loading
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Menu
- [ ] Menu buttons
- [ ] Notification
- [ ] Number input
- [ ] Pagination
- [ ] Popover
- [ ] Progress bar
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Toggletip
- [ ] Tooltip
- [ ] Tree view
- [ ] UI shell header
- [ ] UI shell left panel
- [ ] UI shell right panel
```

**Comment by alisonjoseph** [comment]
duplicate of https://github.com/carbon-design-system/carbon-website/issues/3850
