### ISSUE TITLE
Component Accessibility Status: Usage page

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3850]
### Acceptance Criteria

- Move Live demo to the top
- Status's within ResourceCard
- Question mark tooltip with descriptions of the tiles
- Drop in the new variant switcher https://github.com/carbon-design-system/carbon-website/issues/3847

> [!WARNING]
> Dependent on https://github.com/carbon-design-system/carbon-website/issues/3847

```[tasklist]
### Tasks
- [ ] Update the content template on the contribution page
- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Contained list
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] Dropdown (Dropdown/Multiselect/Combobox)
- [ ] File uploader
- [ ] Form
- [ ] Inline loading
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Menu
- [ ] Menu buttons
- [ ] Notification
- [ ] Number input
- [ ] Pagination
- [ ] Popover
- [ ] Progress bar
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Toggletip
- [ ] Tooltip
- [ ] Tree view
- [ ] UI shell header
- [ ] UI shell left panel
- [ ] UI shell right panel
```
