### ISSUE TITLE
[Selectable Components: Tile] Website Doc

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3861]
### Update the Tile website documentation with what came out of our [final design solutions](https://github.com/carbon-design-system/carbon/issues/14766).

---

### USAGE TAB

**Default preselection content**
> - [x] Change our guidance to not mention we have tiles preselected by default. (If mentioned anywhere)

**Selectable tile images (single select)**
> _Correct any images with the updated visual styling_ 
> - [x] Update the images under: 
>    - [x] [Selectable](https://arc.net/l/quote/xzqgzigp)
>    - [x] "[Example image of how tiles are built on the narrow grid](https://arc.net/l/quote/bvebmhpe)"
>    - [x] [Interactions](https://carbondesignsystem.com/components/tile/usage/#interactions)

---

### STYLE TAB

**Selectable tile images (single select)**
> - [x] Update the images under: 
>    - [x] [Selectable tiles / Single-select](https://arc.net/l/quote/mkszaodj)
>         - [x] Add the disabled state for selected tile as well
>    - [x] [Selectable tiles / Multi-select](https://arc.net/l/quote/zlwsjovy) 
>         - [x] Wrong icon is used under Focus (selected)
>         - [x] Wrong border is there on Hover (selected)
>         - [x] Add the disabled state for selected tile as well
>    - [x] [Structure](https://arc.net/l/quote/xkpgntqg)

**Table content**
> - [x] Add the _Typography_ section under Tile's style
>    - [x] Add a pointer: "`$body-compact-01` is commonly used in tiles, but other type tokens can be used depending on the use case."
> - [x] Update any of the table information to reflect the correct color tokens.

---

- [x] PR Review -> Merge
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/pull/3899
- [ ] https://github.com/carbon-design-system/carbon-website/pull/3901
```
