### ISSUE TITLE
Dividers in components: Website docs - Dropdown Family

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3865]
**_Important Links:_** [Doc Work - Figma File](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=229-12290&mode=design)

## Doc Update for Dropdown Family (mainly Combobox and Filterable Multi-select)

---

**Tasks**

Usage Tab
- [x] - Update 6 Images
- [x] - Mention Guidelines for Vertical Dividers
- [x] - Dos and Donts for Vertical Dividers
- Introduce AI Slug Examples **(note: circle back after AI Doc release)**

Style Tab
- [x] - Update 1 image
- [x] - Update token / colours (Color | Combo box)

Accessibility Tab
- [x] - Update 1 image
- ARIA Guidelines **(note: no ARIA guidelines*)**

**Final Review**

- [x] - Michael Gower's accessibility review
- [x] - VS Code update
- [x] - VS Code review by Lauren
