### ISSUE TITLE
[AI] Investigate how best to incorporate documentation on the website for AI variants 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3925]
## Prompt
**Integrated explorations**
- Investigate where and how to add individual component variant documentation 
   - Does it need to be both on usage and style? How does this affect the length of the style tab?
   - Is it treated similarly to fluid variants?
   - Does the average designer need to know about the AI styles? 
   - How can we clearly communicate who and when someone should use these variants?
- Determine if we need higher-level AI guidance on the website in the form of a Pattern or Guidelines page. 
   - What would be the purpose/goal of that page?
   - Is this where we would reference links to dev assets (react and web components) and documentation? 
   - Where is larger "Designing with AI" content going in the future? Do we just link out to that content instead? 
- Do we need to document the AI tokens alongside the core token or elsewhere? 

---
**Divergent explorations** 
- What if we approach this documentation more independently instead of fully integrated?
   - What if AI had its own L1 section (like data viz) and we addressed usage and styling in a more broad way instead of per component? OR did per component just in this AI section. 
   
## Tasks
- [x] Create example IA, layouts and/or wireframes to illustrate various directions.
- [x] Playback directions to design team (also AI team?)
- [x] Determine course of action (if possible)

**Comment by aagonzales** [comment]
Next steps
- Flesh out example pages 
- Moving forward either with an L1 + component page OR L2 under guidelines + component page
