### ISSUE TITLE
Toggletip vs. Tooltip Docs Guidance Update

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3956]
## Acceptance criteria

- We need to do some research on how we want to structure Tooltip and its variants versus Toggletip.
- There have been discussions about removing the "Standard" Tooltip variant, but also concern if people actually need that use case still and use it in code. We need to first see if we can find valid use cases for this before making the decision of removing it.
  - Ref: [a11y Tooltip ombnibus issue](https://github.com/carbon-design-system/carbon-website/issues/3332)
  - Ref: [a11y Toggletip omnibus issue](https://github.com/carbon-design-system/carbon-website/issues/3334)
- There were also discussions from a11y about only using the information icon in Toggletips and not at all in Standard tooltips, is this valid or are there instances where using the information icon could be used in Tooltips?

### Tasks
- [x] Playback findings to design and a11y team
- [x] Take feedback from playback and align on one direction to move forward with for Toggletip and Tooltip variants
- [ ] Update the Default Tooltip visual in the Storybook

**Comment by sstrubberg** [comment]
@mattrosno can we get metrics on Tooltip usage? variants of tooltip & toggletip.

**Comment by mbgower** [comment]
I found another place where the guidance _must_ be updated in https://carbondesignsystem.com/patterns/forms-pattern/#offering-help

I believe that pretty much everything covered under "Tooltip" here is actually for toggletip. Some of the info under Helper text should also be reviewed.

**Comment by mbgower** [comment]
Here's another great implemented example of how the two are being confused.
https://react.carbondesignsystem.com/?path=/story/components-formlabel--with-tooltip

Two identical looking "i" buttons with completely different behaviour (for mouse, keyboard and touch).

As previously argued, the first, using a tooltip, should not exist. A tooltip's primary (only?) purpose is to expose the name of an icon-only button --that already takes focus in order to allow a user to perform its primary role. This first button does _nothing_  on click, which makes no sense.

In addition, it is also bewildering to a touch user, who is going to click on this first i button and nothing is going to happen.

The second i button works sensibly as a toggletip, operable and understandable to all modalities.

Just changing the border of the i button -- which I think is what is proposed [here](https://github.com/carbon-design-system/carbon/pull/17006)? -- only partially resolves this basic conflation of two interactions.

**Comment by aagonzales** [comment]
Okay, this topic was brought up again today. I think we need to refine our definitions of tooltip and toggle tip. Most of our docs don't align with @mbgower's proposal, which states that the info icon only triggers a toggle-tip. Could differently icons other than a info or help icon trigger a tooltip. Here is an example we have in docs. Because I'm kind of wondering what's the purpose of the [default tooltip ](https://react.carbondesignsystem.com/?path=/story/components-tooltip--default)component if the icon-button tooltip and [definition tooltip](https://react.carbondesignsystem.com/?path=/story/components-definitiontooltip--default) exist as separate components? Is it just a primitive now? And if so how is it different than popover?

**Comment by aagonzales** [comment]
And then there's the ultimate question: can a toggletip use a tooltip? Like this [Help Button](https://gestalt.pinterest.systems/web/helpbutton). Tooltip is the prompt so the user knows to click on it. 

(This is the same problem that also came up with the AI Labe and wither it should have a tooltip even though it already triggers a popover).

**Comment by mbgower** [comment]
>  Could different icons other than an info or help icon trigger a tooltip? 

@aagonzales Yes, any icon button can trigger a tooltip. For that matter, _any_ target can trigger a tooltip. In fact, the `title` property, which causes the browser tooltip (as opposed to Carbon's) can be put on _anything_, whether it is operable or not. This last, however, immediately causes a challenge for a keyboard user (who can never reach something that does not get focus).

>  can a toggletip use a tooltip? 
Yes, the target for the toggletip (the i icon) can have a tooltip --  just like any other control -- and also trigger a toggletip content area.

**Comment by mbgower** [comment]
At the risk of muddying the waters, there are examples of a few overlays in the current github UI worth mentioning, since they help illustrate both trigger considerations as well as questions about the nature of tooltips.

I think when we talk about tooltips, we're talking about a behaviour more than the nature of the information, but there _does_ seem to me to also be an informational divide.

What do I mean? **Behaviourly**, tooltips appear on hover _as well as_ on focus (if they're accessible). It is in some ways an 'unintentional' user action (in that the tooltip appears not because the user necessarily intended to show it, but because their input device encountered a trigger).  **Informationally**,  I think we'd get common agreement that a text-based piece of information resulting from hover is a tooltip. But what if a megamenu appears when I hover over a link in the Header UI Shell (a common behaviour less than a decade ago)? I wouldn't call that a tooltip. I'd call that a poorly implemented component. But there are forms of hover-triggered content which I'd still consider a tooltip, even though it is no longer strictly text. 

Some examples on this page...

First, if you hover over the tag that says "Member" in the upper right corner of this post, you'll see that it has a tooltip that says "This user is a member of the carbon-design-system organization." That is not operable by keyboard (or touch) because there is no actual interaction there, it's just a static tag. I think everyone would agree that this presents as a tooltip (both its styling and the fact it is text-based). It's not giving the name of the tag, since that it is already labelled "Member". So this text is arguably description -- an elaboration of something one can extract from the context. As such, although this tooltip cannot be operated by keyboard, I'd consider it a pretty "lite" failure.
![Image](https://github.com/user-attachments/assets/a7ed4f1d-5fb4-4e85-8d41-48ac7300082b)

A different form of what could be called 'tooltip' exists on this page if you hover over the link below Lauren's prior post, which reads "Toggletip resolve a11y concerns #4358". 
![Image](https://github.com/user-attachments/assets/e5cbac33-8383-498f-a779-3b61330e3be0)

Even though I cannot make this information appear with a keyboard, I can activate the page and get that information. So IMO, this is allowable in 2.1. 1 Keyboard, because there is a keyboard method of getting the same information.

Would I call this preview a tooltip? Probably. It's a descriptive tooltip rather than a name. Then of course the question arises, how is a descriptive tooltip any different than an informational toggletip? The only difference to me is behavioural (how it is operated).

**Comment by sstrubberg** [comment]
REF [Slack thread](https://ibm-studios.slack.com/archives/C0M053VPT/p1725976696528769?thread_ts=1725910590.627519&cid=C0M053VPT)

**Comment by tay1orjones** [comment]
The landscape of all this has shifted quite a bit since we made the decision to have separate tooltip and toggletip components in v11 back in 2021/2022. Much of what you outlined @mbgower is being discussed by standards bodies. Specifically,

* The [Popover `hint` attribute](https://open-ui.org/components/popover-hint.research.explainer/) that has an [open PR](https://github.com/whatwg/html/pull/9778) to add it to the html spec
  * This also has good background links on where "toggletip" vs "tooltip" came from and why the distinction was added in v11.
* [Invokers](https://open-ui.org/components/invokers.explainer/)
* [Interest invokers](https://open-ui.org/components/interest-invokers.explainer/)

For me the most important takeaway from these is this from the Popover hint proposal

> A tooltip should not contain directly-necessary information - that should be placed into the page content directly. It should provide auxiliary or extra information that is available only when the user wants to dig deeper into some content. And that extra information should be able to contain more than just text, since the auxiliary information might very well contain or even be an image or other non-text content.
>
>Note, importantly, that a tooltip does not need to be triggered by hover to be a tooltip. Also note that all things that are hover-triggered are not tooltips. A tooltip is defined by its content, and not how it gets activated.

Whatever we decide should probably map to these ideas to avoid more churn in the future when these features are available in the browser. That feels to me like consolidating Tooltip and Toggletip under a single name, Tooltip, and having it behave like Toggletip does today.

**Comment by mbgower** [comment]
Thanks for all the work on toggletip that resulted in the closure of https://github.com/carbon-design-system/carbon-website/issues/3334

When I was poking around the results at @thyhmdo's request, I noticed that the [default tooltip implementation](https://react.carbondesignsystem.com/?path=/story/components-tooltip--default) on storybook is still using a question mark icon to demo tooltip. I really feel like i and ? icons are exclusively the domain of toggletips. I have never seen them have _any_ other purpose than to reveal instructions/help/context.

**I'd love to get that tooltip example swapped out with an icon-only button** We've removed all references i and ? in the tooltip document. How about using a print, site switcher, or overflow icon-only button? Lots of other options. 

I also think it's a little funny that the other storybook use a labelled button as the trigger for the tooltip. It's not wrong -- and I get that it maybe helps the user understand what they're supposed to do -- but it is a novel :)

---

I think Taylor's info above is important in the broader context of Info Revealed on Hover but I think it can be risky applying comments in that fairly far-ranging discussion without keeping in mind the nuts and bolts of the basic tooltip function. For example it says:
> A tooltip should not contain directly-necessary information - that should be placed into the page content directly.

I guess it really depends on what one considers "directly necessary". The original purpose of a tooltip was to reveal the name of an icon-only button, so that mouse users uncertain of its function could get a text confirmation. By the above quote, one might take it to mean that there should be almost ZERO icon-only buttons, since there are few one can say with certitude are understood by _everyone_.  I don't think that's the author's intent.
This tooltip exists because there are probably _lots_ of people who understand what the icon means and lots of people who do not. IMO, that makes the tooltip "directly necessary" for many users. 

![Image](https://github.com/user-attachments/assets/1639e5ae-8bec-4f01-bbf5-3933df994295)
