### ISSUE TITLE
Giphys: Cover art

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3961]
As of today there are 23 gifs used across 14 pages that need static "cover art" images made:

```[tasklist]
### Tasks
- [x] Create or find 23 images that match the gifs
- [x] Update the code with static images
- [x] Review
```

-----

- [x] src/pages/community/patterns/create-flows/index.mdx:

```
83  <img
84:   src="/images/InlineCreateExample.gif"
85    alt="Animated inline create example"

286  
287: ![Wide tearsheet animated Create flow](images/WideTearsheetAnimated.gif)
288  

320  
321: ![Wide tearsheet animated options toggle](images/WideTearsheetShowAllOptionsAnimated.gif)
322  
```

- [x] src/pages/components/data-table/usage.mdx:

```
475  
476: ![data table search](images/datatable_search.gif)
477  
```

- [x] src/pages/components/notification/usage.mdx:

```
251  
252: ![Example of toast notification placement](images/05_toast_context_608.gif)
253  
```

- [x] src/pages/components/progress-bar/usage.mdx:

```
122  
123: ![Determinate progress bars fill from 0 to 100%.](images/progress-bar-usage-2.gif)
124  

131  
132: ![Indeterminate progress bars move along a fixed track continually until the process is complete.](images/progress-bar-usage-3.gif)
133  
```

- [x] src/pages/components/text-input/usage.mdx:

```
433  
434: ![Example of an error state being triggered](images/text-input-usage-2.gif)
435  
```

- [x] src/pages/components/UI-shell-header/usage.mdx:

```
249  
250: ![hint text](images/skip-to-main-content.gif)
251  
```

- [ ] src/pages/contributing/get-started.mdx:

```
55    alt="words"
56:   src="/images/carbon-tutorial.gif"
57  />

71    alt="words"
72:   src="/images/two-handle-slider.gif"
73  />

87    alt="words"
88:   src="/images/left-hand-nav-delay.gif"
89  />

103    alt="words"
104:   src="/images/read-only-form-inputs.gif"
105  />

119    alt="words"
120:   src="/images/icon-only-switcher.gif"
121  />

135    alt="words"
136:   src="/images/combo-button.gif"
137  />
```

- [x] src/pages/designing/kits/sketch.mdx:

```
186  
187: ![2x Grid overview](/images/grid-2.gif)
188  
```

- [x] src/pages/migrating/guide/design.mdx:

```
85  
86: ![Example of toast notifications stacking.](images/05_toast_context_608.gif)
87  
```

- [x] src/pages/patterns/forms-pattern/index.mdx:

```
593  
594: ![Example of client-side error message](/images/inline-error-message.gif)
595  

611  
612: ![Example of server-side](/images/server_side.gif)
613  
```

- [x] src/pages/patterns/global-header/index.mdx:

```
376  
377: ![hint text](images/skip-to-main-content.gif)
378  
```

- [x] src/pages/patterns/loading-pattern/index.mdx:

```
115  
116: ![Example of an inline loading indicator](/images/inline-loading-animated.gif)
117  
```

- [x] src/pages/patterns/notification-pattern/index.mdx:

```
249  
250: ![Toast notification in a product](/images/4_toast_736.gif)
251  
```

- [x] src/pages/patterns/overflow-content/index.mdx:

```
188  
189: ![Example of a Code Snippet utilizing the “Show more” Button.](images/show-more.gif)
190  
```
