### ISSUE TITLE
[Feature flags] Website Documentation ☂️

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3994]
## Acceptance criteria

With the implementation of Feature Flags for some of our components, we need to create website documentation to explain feature flags in a general way somewhere on the website and document which components have feature flags for individual components.

```[tasklist]
### Research and design iterations
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3999
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4153
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4186
```

```[tasklist]
### Website docs
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3975
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4224
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4225
- [ ] https://github.com/carbon-design-system/carbon-website/issues/3993
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4223
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4226
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4222
```
