### ISSUE TITLE
Carbon for AI design documentation ☂️ 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3997]
Add documentation for the new Carbon for AI work to the website. Content will appear in various appropriate places throughout the website, including a new L2 section under guidelines. 

```[tasklist]
### General website enhancements
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4007
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4008
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4057
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4058
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4072
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4174
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4110
```

```[tasklist]
### AI Guidelines page
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4006
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4055
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4056
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4063
- [x] AI Guidelines: Review content in Figma with the AI team
- [x] AI Guidelines: Create PR for website
- [x] AI Guidelines: update "slug" name and coming soon in component pages.
```
```[tasklist]
### AI label "slug" component page
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4062
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4130
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4131
```

```[tasklist]
### Component page updates
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4009
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4011
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4012
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4035
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4036
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4037
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4038
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4040
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4039
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4010
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4041
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4129
```
