### ISSUE TITLE
Move to core: Illustration library

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-website#4141]
Illustrations need a single place where everyone can find the files as well as usage guidance. This is especially important given that there is a workstream around 'one IBM' and we are moving away from hero branding illustrations. The goal of this issue is to unify illustrations and guide people on which ones to use.

Acceptance criteria:
- [ ] Move the [Illustrations](https://pages.github.ibm.com/cdai-design/pal/illustrations/library) page to Core
- [ ] Ensure that the illustrations found here are still relevant to IBM's branding
- [ ] Add additional guidance/when to use. 404 illustration is a great example of having a perspective. i.e. grayscale instead of color
```[tasklist]
### Tasks
- [ ] Move the Illustrations page to Core
- [ ] Ensure that the illustrations found here are still relevant to IBM's branding
- [ ] Add additional guidance/when to use. 404 illustration is a great example of having a perspective. i.e. grayscale instead of color
- [ ] https://github.com/carbon-design-system/ibm-products/issues/5611
```

**Comment by laurenmrice** [comment]
@aubrey-oneal System squad discussed this in our Issue Refinement meeting. Could you and others from the PAL side run this idea by Jeannie and Mike of where the Illustration page should go? We were also wondering if it should be on IDL instead, or is it too product specific.
