### ISSUE TITLE
[DoD]: Carbon Labs added to IA

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#4181]
### Summary

We would like to add a dedicated page to the Carbon website called "Carbon Innovation." Ideally this will be a field of tiles containing multiple links that take users to assets related to various workstreams that are still in Discovery. The assets will very depending upon the workgroup/team/discipline. Git, storybook, mural, slack channel etc.

### Justification

There is a pressing need for our users to be able to find work that is still in discovery/exploration, rather than waiting for it to be complete. This need is even more pressing now that the Product PAL has gated the addition of new assets and is trying to adhere to the definition of done. 

### Tasks

- [x] Settle on the name ~"Carbon Innovation"~ Carbon Labs
- [x] Need a comprehensive list of the work we want to showcase here and the associated links/content
- [x] Figure out how to slot it into the IA
- [x] Write Overview content explaining the purpose of the Carbon Innovation Program & what to expect of the content, how to engage, rewards for contribution etc. 
- [x] Need codified definiton of done on the site and need to describe what the process going from discovery to launch and scale
- [x] Identify a list of core and optional assets that will be associated with the workgroups (e.g. **core:** github ticket, slack channel, team names **optional** Mural, storybook, Figma, PAL link for PLG? etc.)
- [x] Design tiles that link out to each ongoing innovation effort (list of things you'd like to be on the cards)
- [x] Specify most content is IBMers only

### Specific timeline issues / requests

September 11, this is when we're also launching the update product PAL site.

**Comment by carrenelloyd** [comment]
This is a list of current Workgroups. I will add additional links to resources as we go.

1. Carbon for AI
2. PLG
3. Calendar
4. Canvas 
5. Conditions Builder 
6. Filtering
7. Empty State 
8. AI Chat

**Comment by jeanservaas** [comment]
I think by the time this goes up Condition Builder will be live on PAL.

**Comment by carrenelloyd** [comment]
Other guilds that might be nice to list here (transparency) and also give the community a chance to join or give feedback
1. Content guild
2. Illustration guild
3. Data visualization guild

**Comment by carrenelloyd** [comment]
This Airtable tracks details related to the workgroups: https://airtable.com/invite/l?inviteId=invwzFCaZ57YC53oo&inviteToken=2fdebaae3276b90a5d5eaa2dc5bacbed628ec1176f9f7ec20b4193023cc87442&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts
