### ISSUE TITLE
Definition of Done ⛱️ 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#4202]
## Justification:

After several workshops and the Carbon/C4IBMP merger, there is a clear process that all future innovation/contribution must follow in adherence with the IBM's Product Development Lifecycle. The greater Carbon community needs to understand this process, especially since there is a publishing gate on the Product PAL now. 

The purpose of this documentation is to explain the PDLC as it relates to Carbon to the community and then provide a clear checklist for contributors, so that they know what we mean be stable, we are aligned on expectations etc.

The goal is to publish this by the September 11th release of the new PAL site (on both the Carbon site and the C4IBMP site).

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4229
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4230
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4256
- [x] [DoD] Create images to illustrate PDLC concepts
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4294
- [ ] https://github.com/carbon-design-system/carbon-website/issues/4181
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/872
- [ ] [DoD] Add LTS and deprecation info (Later task)
```
<details>
  <summary>Originial tasks</summary>

## Tasks

- [x]  **Figure out the IA on both the Carbon and the Product PAL sites.** There is another [issue](https://github.com/carbon-design-system/carbon-website/issues/4181), re: Carbon innovation that relates to this issue (see below); both pages need to be accounted for in the IA. We're aiming for the Contribution section to house both of these new pages...but this is a bit of a branding issue. Do we want to use the name Carbon Innovation (instead of Contribution) do we want to call all innovation "Carbon Labs?" Do we want to actually use the name Product Development Lifecycle in the IA? You get the picture. 

- [x] **Vet code content checklist with devs** The code checklist (esp. the API best practices) is pretty heavy at the moment; also, the testing checklist could potentially be broken up into another section. Have them review and try to simplify it.

- [x] **Vet design kit checklist with Juan and Rich** This section is the most incomplete part of the checklist...probably because the Figma guild has it's own checklist for kit contributions and we're trying to kind of shorthand their checklist on our site. I think we need to decide whether we want to bring a shortened version of their checklist over here to the site, or just link out to it. 

- [x] **Provide PDLC images here** @jeanservaas can help with this. I think we need to decide whether we just want one image of the full PDLC or if we also want an image per phase.

- [ ] **Finalize the content** @aubrey-oneal provided the original version of this content in box and @jeanservaas pushed it further and fleshed it out in context. I'd like Aubrey and Anna to further review what I've done, assess the order of things, read my notes and finalize the content. 

</details>

## Related issues:
https://github.com/carbon-design-system/ibm-products/issues/4996

https://github.com/carbon-design-system/carbon-website/issues/4181

## Resources:

Aubrey's boxtnote
https://ibm.ent.box.com/notes/1532682148666

Figma file
https://www.figma.com/design/tI8fN4VQY90CQenDECTlCV/Definition_of_done?node-id=0-1&t=vxVpqYp7aYmr9ne3-1
