### ISSUE TITLE
Bug: Update design kit names

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#4297]
Recently the names of several design kits have been updated. We need to make sure the everywhere on the site where we mention a kit name is updated to match the new names in Figma. 

```[tasklist]
### Tasks
- [x] Audit the site and kits to ensure parity
- [x] Open a PR with the changes
- [x] Update the Figma thumbnail
```

## Name changes
- [x] `(v11) All themes - Carbon Design System` updated to `(v11) Carbon Design System`
- [x] _Find others from audit task and list here_

## Locations on the website to check
- [Designing/Design kits](https://carbondesignsystem.com/designing/kits/figma/)
- [Designing/Other resources ](https://carbondesignsystem.com/designing/design-resources/)
- _Find others places from audit task and list here_
