### ISSUE TITLE
Carbon X Website launch checklist

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#804]
- [ ] Add clear documentation to website arounnd v9/v10 components with link to v9 site _(The v10 website is launching before we release v10 `carbon-components`. )_
- [x] Publish current website to `v9.carbondesignsystem.com` _with banner at the top similar to http://v8.carbondesignsystem.com/_
- [x] Create `v9` branch on github for v9 code
- [ ] Merge v10 branch to master 
- [ ] Update circle ci config
- [ ] Internal site carbondesignsystem-internal.stage1.mybluemix.net / w3.ibm.com/design/product
- [ ] External site www.carbondesignsystem.com & www.ibm.com/design/product (redirect to carbon domain)
