### ISSUE TITLE
Guidelines documentation (elements packages)

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#841]
Developer guidelines around how to use our elements packages are lacking or completely missing from the website. 

- Color
- Icons
- Pictograms
- Motion
- Typography

These pages need an "Implementation" tab added, similar to the Grid page (https://www.carbondesignsystem.com/guidelines/2x-grid/implementation) so a developer coming to the website will know how to use the packages in their code.

**Comment by connor-leech** [comment]
## To-do
- [ ]  Bring over README files into code tabs (or elements docs when applicable)
    - [ ]  Colors
    - [ ]  Grid
    - [ ]  Icons
    - [ ]  Layout
    - [ ]  Themes
    - [ ]  Type
    - [ ]  Pictograms
- [ ]  Clean up readme docs
    - [ ]  Colors
    - [ ]  Grid
    - [ ]  Icons
    - [ ]  Layout
    - [ ]  Themes
    - [ ]  Type
    - [ ]  Pictograms
- [ ]  Speak with Alison and Josh about each tab. What's missing? What does a dev need to know? Is any imagery missing?
    - [ ]  Colors
    - [ ]  Grid
    - [ ]  Icons
    - [ ]  Layout
    - [ ]  Themes
    - [ ]  Type
    - [ ]  Pictograms
- [ ]  Get content review on all new pages
    - [ ]  Colors
    - [ ]  Grid
    - [ ]  Icons
    - [ ]  Layout
    - [ ]  Themes
    - [ ]  Type
    - [ ]  Pictograms
- [ ]  Get design review on all new pages
    - [ ]  Colors
    - [ ]  Grid
    - [ ]  Icons
    - [ ]  Layout
    - [ ]  Themes
    - [ ]  Type
    - [ ]  Pictograms

## Questions

- Why isn't layout on the website? Is that spacing instead? If so, they shouldn't be named the same thing.
- Why do pictograms and icons have their own contribute tab? This isn't the same pattern as we follow elsewhere on the site.
    - How many icons are contributed via this link? We should add fathom tracking to those links.

**Comment by janchild** [comment]
This work has been completed.
