### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#864]
### Polish of newly published patterns (Q1)

- [ ] Dev review, accessibility concerns
- [ ] Image review and polishing, streamline
- [ ] Incorporating feedback from GT and SMEs

### Re-format existing core patterns (January)

Two-phased approach:
1. Minimum: get content into new layout with headings by end of January.
2. Dive deep to augment this existing content

- [ ] Common actions
- [ ] Filtering
- [ ] Loading
- [ ] Overflow content

Disabled states is going to need more research

### Still to do from [original list](https://ibm.ent.box.com/notes/548098235777) of patterns

**Main group**

- Error states

**Stretch**

- Guide (includes Onboarding)
- Pagination
- Profile
- Table
- Text toolbar

**Backburner / Approach to be considered (per Dec 2019 GT meeting)**
- Dashboards

### Watson Moment components/patterns from Maui
Need to look at these and determine where they live. Probably need tertiary navigation to do it properly. 
In the Watson Experience guide, and then we have a reference out to it from somewhere. 
- Watson Moments Overview https://github.ibm.com/data-and-ai/WatsonMoments/issues/84
- Watson Insights https://github.ibm.com/data-and-ai/WatsonMoments/issues/85
- Watson Moments components and Sketch kit https://github.ibm.com/data-and-ai/WatsonMoments/issues/86

### Experimental patterns to review for core Carbon

- Cards
- Chatbots (Jan to work with Tom Roach and Ethan Winters) https://github.com/carbon-design-system/carbon-website/issues/1272
- Order summary: 
From Mike: This seems a good one to tackle sometime in 2020. Shixie was working on something with an order summary as well.
https://pages.github.ibm.com/CDAI-design/CDAI-design-website/patterns/order-summary/usage

### Other patterns

- Onboarding (multi-pattern). Jan working with Scott Robinson, Jennifer Schofeldt, and Sophia Levens to define.
- Text toolbar: https://github.com/carbon-design-system/carbon/issues/2447 
- Page header: https://pages.github.ibm.com/CDAI-design/CDAI-design-website/components/page-header 
- Pagination
- Slide-in and slide-over panels: https://pages.github.ibm.com/CDAI-design/CDAI-design-website/components/slide-in-panel/
https://pages.github.ibm.com/CDAI-design/CDAI-design-website/components/slide-over-panel/usage 
- Tables (Virginia and Tracey working on this)
- Guide
- Page content types (headings, tooltips, labels, placeholder text, links to documentation, onboarding) Jan to define
- Tiles (See Cloud PAL)
- Status icons (https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons)

### Patterns with code 

Discussion with Robin and Matt about providing code with some of these patterns:

- header
- shell
- login
- table
- footer
- search
- side panels/dialogs
- chatbot
- Edit
- import
- Export
- Dashboard widgets
